export { default as Home } from './home'
export { default as All } from './all'
export { default as Muse } from './muse'
export { default as UserUpdate} from './userUpdate'
export { default as MyPage} from './myPage'
export { default as Replace } from './replace'